name: Release Workflow
on:
  push:
    branches:
    - develop
    - 'release/**'

jobs:
  setup-develop:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    steps:
    - name: Wait for build to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Build Job'
        repo-token: ${{ github.token }}
        wait-interval: 10
        allowed-conclusions: success
    - name: Wait for e2e to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'e2e Job'
        repo-token: ${{ github.token }}
        wait-interval: 10
        allowed-conclusions: success

